services:
  proxy:
    image: nginx:alpine
    container_name: ossop-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../../config/certs:/etc/nginx/certs:ro
    networks:
      - ossop-network
    restart: unless-stopped

networks:
  ossop-network:
    external: true
